/** Shared Playwright selectors for e2e specs. */
export const selectors = {
  searchInput: '[aria-label="Search shows"]',
  clearSearch: '[aria-label="Clear search"]',
  viewToggle: '[aria-label="View options"]',
  phraseFilter: '[aria-label="Filter by phrase count"]',
  showsGrid: '.shows-grid',
  showsList: '[aria-label="Shows list"]',
  showCard: (title: string) => `[data-testid="show-card"][data-show-title="${title}"]`,
  showListRow: (title: string) => `[data-testid="show-row"][data-show-title="${title}"]`,
  bingoGrid: '[data-testid="bingo-grid"]',
  bingoCell: (index: number) => `[data-testid="bingo-cell-${index}"]`,
  regenerateButton: '[data-testid="regenerate-bingo"]',
  resetMarksButton: '[data-testid="reset-marks"]',
  backToShows: '.back-link',
  editShowLink: '.edit-show-link',
  createShowLink: '.add-show-link',
  cancelButton: '[aria-label="Cancel and return"], .cancel-btn',
  createShowSubmit: '[aria-label="Create show"]',
  saveShow: '[aria-label="Save show changes"]',
  showTitleInput: '#show-title-input',
  gameTitleInput: '#game-title-input',
  centerSquareInput: '#center-square-input',
  newPhraseInput: '#new-phrase-input',
  addPhraseButton: '[aria-label="Add new phrase"]',
  bulkToggle: '.bulk-toggle-btn',
  bulkPhrasesInput: '#bulk-phrases-input',
  bingoAlert: '.bingo-alert'
}
