package org.bomartin.tvbingo;

import io.zonky.test.db.AutoConfigureEmbeddedDatabase;
import io.zonky.test.db.AutoConfigureEmbeddedDatabase.DatabaseProvider;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.dao.DataAccessException;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.test.context.ActiveProfiles;

import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * Regression test for the production "Database constraint violation" bug.
 *
 * <p>The baseline shows (changeSet 04) are inserted with explicit ids 1-7 into an
 * identity column. Inserting explicit values does not advance the identity
 * sequence, so the first application insert reuses id 1 and fails with a
 * primary-key violation. changeSet 05 resyncs the sequence past the max id.
 *
 * <p>This test reproduces the exact failure mode against embedded Postgres using
 * production-like DDL (a {@code GENERATED ... AS IDENTITY} column, matching
 * Liquibase {@code autoIncrement}, rather than the {@code BIGSERIAL} used by the
 * other tests' test-schema.sql) and verifies the resync SQL from changeSet 05
 * fixes it. It re-declares the DDL because the application's Liquibase changelog
 * requires the tvbingo_schema to be created externally before connecting (done
 * by setup-postgres.sh in production), which the embedded context cannot do.
 */
@SpringBootTest
@AutoConfigureEmbeddedDatabase(provider = DatabaseProvider.ZONKY)
@ActiveProfiles("test")
class ShowsIdSequenceMigrationTest {

    // Mirrors the resync SQL in db/changelog/changes/04-resync-shows-id-sequence.yaml
    private static final String RESYNC_SQL =
            "SELECT setval(pg_get_serial_sequence('tvbingo_schema.shows', 'id'), "
            + "(SELECT COALESCE(MAX(id), 1) FROM tvbingo_schema.shows))";

    @Autowired
    private JdbcTemplate jdbc;

    @Test
    void resyncSql_fixesPrimaryKeyCollisionAfterExplicitIdInserts() {
        // Production-like schema: identity column (not BIGSERIAL), so explicit-id
        // inserts leave the sequence un-advanced, exactly like changeSet 04.
        jdbc.execute("CREATE SCHEMA IF NOT EXISTS tvbingo_schema");
        jdbc.execute("DROP TABLE IF EXISTS tvbingo_schema.shows CASCADE");
        jdbc.execute("CREATE TABLE tvbingo_schema.shows ("
                + "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
                + "show_title VARCHAR(255) NOT NULL)");
        for (int i = 1; i <= 7; i++) {
            jdbc.update("INSERT INTO tvbingo_schema.shows (id, show_title) VALUES (?, ?)",
                    i, "Baseline " + i);
        }

        // Reproduce the bug: a generated-id insert reuses id 1 and collides.
        assertThrows(DataAccessException.class, () ->
                jdbc.update("INSERT INTO tvbingo_schema.shows (show_title) VALUES ('collides')"),
                "expected a primary-key violation before the sequence is resynced");

        // Apply the changeSet 05 fix.
        jdbc.execute(RESYNC_SQL);

        // Now a generated-id insert gets a fresh id past the baseline and succeeds.
        Long newId = jdbc.queryForObject(
                "INSERT INTO tvbingo_schema.shows (show_title) VALUES ('after resync') RETURNING id",
                Long.class);
        assertNotNull(newId, "insert should return a generated id");
        assertTrue(newId > 7, "new id should be past the baseline ids (1-7), was " + newId);
    }
}
